version: '3.8'

services:
  db:
    image: mariadb:10.9
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      disable: true

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_started

volumes:
  db_data: